### PR TITLE
Add an option to improve image appearance on hidpi displays.

### PR DESCRIPTION
**Pull request by sprang**

### CODE REVIEW

**Comment by zk-phi** [comment]
how does this differ from

````
(setq symon-sparkline-height (* symon-sparkline-height 2)
      symon-sparkline-width (* symon-sparkline-width 2))
````

?

**Comment by sprang** [comment]
My patch makes the pixels larger (versus just increasing the area). My
laptop screen is almost 300 dots/inch, so the default rendering was very
delicate. This is sort of like setting the line width to 2.

-Steve

zk_phi writes:

> how does this differ from
>
> ````
> (setq symon-sparkline-height (* symon-sparkline-height 2)
>       symon-sparkline-width (* symon-sparkline-width 2))
> ````
>
> ?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zk-phi/symon/pull/17#issuecomment-73408558

--

**Comment by zk-phi** [comment]
thanks for your contribution.
this seems fine as a workaround, but we should implement `symon-sparkline-line-width` later because in order to render sparklines faster and better.
(for example, when we have history-size set 100 and sparkline-width 50, then 50 samples are dropped on rendering, but when we have sparkline-width 100 then all samples are rendered)

**Comment by zk-phi** [comment]
implemented. now

````
(setq symon-sparkline-height    (* symon-sparkline-height 2)
      symon-sparkline-width     (* symon-sparkline-width 2)
      symon-sparkline-thickness (* symon-sparkline-thickness 2))
````

works like `(setq symon-hidpi-display t)`.

**Pull request merged**
